name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate changelog
      id: changelog
      run: |
        echo "## What's Changed" >> $GITHUB_STEP_SUMMARY
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> $GITHUB_STEP_SUMMARY

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release
          ${{ steps.changelog.outputs.changelog }}
          
          ## Docker Images
          - Backend: `ghcr.io/${{ github.repository }}-backend:${{ github.ref_name }}`
          - Frontend: `ghcr.io/${{ github.repository }}-frontend:${{ github.ref_name }}`
          
          ## Installation
          ```bash
          docker pull ghcr.io/${{ github.repository }}-backend:${{ github.ref_name }}
          docker pull ghcr.io/${{ github.repository }}-frontend:${{ github.ref_name }}
          ```
        draft: false
        prerelease: false
